name: Serverutils
version: ${project.version}
main: me.mlhmz.serverutils.Serverutils
api-version: 1.16
authors: [Paym]
description: Serverutils

commands:
  build:
    description: Schalter für den Build-Modus
    aliases: [b]
  spawnutils:
    description: Utilitys fuer die Spawn und Teleportfunktionen
  spawn:
    description: Teleportiert dich zum festgelegten Spawn
    aliases: [s]
